version: '3'

services:
  app-dev:
    image: swoldanski/python-sandbox
    build: .
    user: "1000:999"
    volumes:
    - ./src:/code
    labels:
      - "author=swoldanski"
    command: watch -t pytest -v
  
  app:
    image: swoldanski/python-sandbox
